version: '3'
services:
  chatgpt-telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
#      - telegram-bot-api-data:/var/lib/telegram-bot-api
    restart: unless-stopped

#  telegram-bot-api:
#    image: aiogram/telegram-bot-api:latest
#    environment:
#      TELEGRAM_LOCAL: 1
#    env_file:
#      - .env
#    volumes:
#      - telegram-bot-api-data:/var/lib/telegram-bot-api
#    ports:
#      - 8081:8081

#volumes:
#  telegram-bot-api-data:
